version: '3.7'

services:
  api:
    container_name: GestorCompras
    image: node:20-alpine
    # això del final és una pirula per a que el contenedor no es tanqui després del install # && npm run start"
    environment:
      - CHROMIUM_PATH=/usr/bin/chromium-browser
    command: sh -c "apk add --no-cache chromium nss freetype harfbuzz ttf-freefont && npm run start"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"   # Tamaño máximo de cada archivo de log
        max-file: "1"     # Número máximo de archivos de log
    ports:
      - '3037:3037'
    restart: always
    working_dir: /app
    volumes:
      - .:/app
